apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-aws
  name: capa-serving-cert
  namespace: capa-system
spec:
  dnsNames:
  - capa-webhook-service.capa-system.svc
  - capa-webhook-service.capa-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: capa-selfsigned-issuer
  secretName: capa-webhook-service-cert
