bootstrap:
  image:
    tag: 2.11
    url: quay.io/edge-infrastructure/cluster-api-bootstrap-provider-openshift-assisted
controlplane:
  image:
    tag: 2.11
    url: quay.io/edge-infrastructure/cluster-api-controlplane-provider-openshift-assisted
