bootstrap:
  image:
    tag: latest
    url: quay.io/edge-infrastructure/cluster-api-bootstrap-provider-openshift-assisted
controlplane:
  image:
    tag: latest
    url: quay.io/edge-infrastructure/cluster-api-controlplane-provider-openshift-assisted
global:
  deployOnOCP: true
