apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-metal3
  name: mce-capm3-selfsigned-issuer
  namespace: multicluster-engine
spec:
  selfSigned: {}
