apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-metal3
  name: mce-capm3-serving-cert
  namespace: multicluster-engine
spec:
  commonName: mce-capm3-webhook-service.multicluster-engine.svc
  dnsNames:
  - mce-capm3-webhook-service.multicluster-engine.svc
  - mce-capm3-webhook-service.multicluster-engine.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: mce-capm3-selfsigned-issuer
  secretName: mce-capm3-webhook-service-cert
