apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-metal3
  name: capm3-serving-cert
  namespace: '{{ .Release.Namespace }}'
spec:
  commonName: capm3-webhook-service.{{ .Release.Namespace }}.svc
  dnsNames:
  - capm3-webhook-service.{{ .Release.Namespace }}.svc
  - capm3-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: capm3-selfsigned-issuer
  secretName: capm3-webhook-service-cert
