apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
    service.beta.openshift.io/serving-cert-secret-name: capz-webhook-service-cert
  labels:
    cluster.x-k8s.io/provider: infrastructure-azure
  name: capz-webhook-service
  namespace: capz-system
spec:
  ports:
  - port: 443
    targetPort: webhook-server
  selector:
    cluster.x-k8s.io/provider: infrastructure-azure
