# Resource: core_v1_service_capm3-system_capm3-webhook-service
---
{{- if .Values.global.deployOnOCP }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: capm3-webhook-service-cert
  labels:
    cluster.x-k8s.io/provider: infrastructure-metal3
  name: capm3-webhook-service
  namespace: capm3-system
spec:
  ports:
  - port: 443
    targetPort: webhook-server
  selector:
    cluster.x-k8s.io/provider: infrastructure-metal3
{{- else }}
apiVersion: v1
kind: Service
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-metal3
  name: capm3-webhook-service
  namespace: capm3-system
spec:
  ports:
  - port: 443
    targetPort: webhook-server
  selector:
    cluster.x-k8s.io/provider: infrastructure-metal3
{{- end }}