# Resource: rbac.authorization.k8s.io_v1_clusterrolebinding_capm3-manager-rolebinding
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-metal3
  name: capm3-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: capm3-manager-role
subjects:
- kind: ServiceAccount
  name: capm3-manager
  namespace: capm3-system