# Resource: rbac.authorization.k8s.io_v1_rolebinding_capm3-system_capm3-leader-election-rolebinding
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-metal3
  name: capm3-leader-election-rolebinding
  namespace: capm3-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: capm3-leader-election-role
subjects:
- kind: ServiceAccount
  name: capm3-manager
  namespace: capm3-system
