apiVersion: v2
name: cluster-api-provider-openshift-assisted
description: Cluster API Bootstrap and Controlplane providers for OpenShift Assisted Installer
type: application
version: "2.11"
appVersion: "2.11"
