bootstrap:
  image:
    tag: 2.11
    url: quay.io/edge-infrastructure/cluster-api-bootstrap-provider-openshift-assisted
    webhook:
      certificate:
        namespace: multicluster-engine
        name: mycert
controlplane:
  image:
    tag: 2.11
    url: quay.io/edge-infrastructure/cluster-api-controlplane-provider-openshift-assisted
