manager:
  cmd: /bin/cluster-api-controller-manager
  image:
    tag: v4.19
    url: registry.redhat.io/openshift4/ose-cluster-api-rhel9
webhook:
  image:
    tag: v2.9.0
    url: registry.redhat.io/multicluster-engine/mce-capi-webhook-config-rhel9
