manager:
  cmd: /manager
  image:
    tag: v4.21
    url: registry.redhat.io/openshift4/ose-cluster-api-rhel9
webhook:
  image:
    tag: 2.11.0-1
    url: registry.redhat.io/multicluster-engine/mce-capi-webhook-config-rhel9
