apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    cluster.x-k8s.io/provider: cluster-api
  name: capi-serving-cert
  namespace: '{{ .Release.Namespace }}'
spec:
  commonName: capi-webhook-service.{{ .Release.Namespace }}.svc
  dnsNames:
  - capi-webhook-service.{{ .Release.Namespace }}.svc
  - capi-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: capi-selfsigned-issuer
  secretName: capi-webhook-service-cert
  subject:
    organizations:
    - k8s-sig-cluster-lifecycle
