apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app.kubernetes.io/name: azure-service-operator
    control-plane: azureserviceoperator-controller-manager
  name: azureserviceoperator-pdb
  namespace: '{{ .Release.Namespace }}'
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      control-plane: azureserviceoperator-controller-manager
